# Indspeech-news-tts

## Audio Length

In [1]:
import os
import torch
import torchaudio
import dac
from tqdm import tqdm
import pandas as pd


import os
os.environ["CUDA_VISIBLE_DEVICES"] = "2"

wav_dir = "/mnt/ssd/nafish/text-to-speech/data/indspeech_news_tts/wavs"
device = "cuda" if torch.cuda.is_available() else "cpu"

dac_model = dac.DAC.load(dac.utils.download()).to(device)

wav_files = [os.path.join(wav_dir, f) for f in os.listdir(wav_dir) if f.lower().endswith(".wav")]

lengths = []
for path in tqdm(wav_files, desc="Processing audio"):
    try:
        wav, sr = torchaudio.load(path)
        wav = wav.to(device)
        with torch.inference_mode():
            result = dac_model.encode(wav.unsqueeze(0))
            codes = result[0] if isinstance(result, tuple) else result
            T = codes.shape[-1]
            lengths.append(T)
    except Exception as e:
        print(f"❌ Error on {path}: {e}")

series = pd.Series(lengths)
print("\n=== Audio Frame Stats (DAC tokens) ===")
print(f"Total files : {len(lengths)}")
print(f"Max         : {series.max()}")
print(f"95th %ile   : {int(series.quantile(0.95))}")
print(f"Mean        : {int(series.mean())}")
print(f"Min         : {series.min()}")

/home/atmatech/.pyenv/versions/3.10.13/envs/dia-vox/lib/python3.10/site-packages/torch/nn/utils/weight_norm.py:143: FutureWarning: `torch.nn.utils.weight_norm` is deprecated in favor of `torch.nn.utils.parametrizations.weight_norm`.
  WeightNorm.apply(module, name, dim)
Processing audio: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2012/2012 [01:09<00:00, 29.05it/s]

=== Audio Frame Stats (DAC tokens) ===
Total files : 2012
Max         : 468
95th %ile   : 232
Mean        : 148
Min         : 23

## Text Length

In [24]:
import pandas as pd

csv_path = "/mnt/ssd/nafish/text-to-speech/data/indspeech_news_tts/dia_dataset.csv"

df = pd.read_csv(csv_path, sep="|", header=None, names=["audio_path", "text"])

# hitung panjang dalam byte
byte_lengths = df["text"].apply(lambda x: len(str(x).encode("utf-8")))
series = byte_lengths

print("\n=== Text Byte Stats (Dia-1.6B style) ===")
print(f"Total samples: {len(series)}")
print(f"Max bytes    : {series.max()}")
print(f"95th %ile    : {int(series.quantile(0.95))}")
print(f"Mean bytes   : {int(series.mean())}")
print(f"Min bytes    : {series.min()}")

=== Text Byte Stats (Dia-1.6B style) ===
Total samples: 2012
Max bytes    : 153
95th %ile    : 79
Mean bytes   : 50
Min bytes    : 5

In [25]:
df

             audio_path                                               text
0     SPK00_F_0000.wav    Reaksi berbeda disampaikan penasihat hukum pe...
1     SPK00_F_0001.wav    Konflik eksekutif-legislatif sebenarnya adala...
2     SPK00_F_0002.wav    Jenderal TNI Endriartono Sutarto memuji sosok...
3     SPK00_F_0003.wav    Ketua fraksi PDIP Arifin Panigoro dan Yusril ...
4     SPK00_F_0004.wav    Yakni Gubernur Sutiyoso, Djaelani, Fauzi Bowo...
...                 ...                                                ...
2007  SPK00_F_2007.wav                                    Saya minta itu.
2008  SPK00_F_2008.wav                 Saya telah kehilangan paspor saya.
2009  SPK00_F_2009.wav    Di mana saya dapat memesan tempat duduk keret...
2010  SPK00_F_2010.wav    Bisakah anda menukarkan barang ini dengan yan...
2011  SPK00_F_2011.wav    Seratus dua puluh tiga, delapan tujuh enam li...

[2012 rows x 2 columns]

## Audio Duration

In [3]:
import torchaudio
import os

def get_total_audio_duration_and_count(folder_path, extensions={".wav", ".mp3", ".flac"}):
    total_seconds = 0.0
    file_count = 0
    for root, _, files in os.walk(folder_path):
        for file in files:
            if any(file.lower().endswith(ext) for ext in extensions):
                path = os.path.join(root, file)
                try:
                    waveform, sample_rate = torchaudio.load(path)
                    duration = waveform.shape[1] / sample_rate
                    total_seconds += duration
                    file_count += 1
                except Exception as e:
                    print(f"Failed to load {file}: {e}")
    total_hours = total_seconds / 3600
    return total_hours, file_count

# Ganti dengan path ke folder kamu
folder = "/mnt/ssd/nafish/text-to-speech/data/indspeech_news_tts/wavs"
hours, count = get_total_audio_duration_and_count(folder)
print(f"Total audio duration: {hours:.2f} hours")
print(f"Total number of audio files: {count}")

Total audio duration: 1.93 hours
Total number of audio files: 2012

# CommonVoice-17

## Audio Length

In [4]:
import os
import torch
import torchaudio
import dac
from tqdm import tqdm
import pandas as pd


import os
os.environ["CUDA_VISIBLE_DEVICES"] = "2"

wav_dir = "/mnt/ssd/ifa/text-to-speech/IMS-Toucan/Data/dataset_commonvoice/wav"
device = "cuda" if torch.cuda.is_available() else "cpu"

dac_model = dac.DAC.load(dac.utils.download()).to(device)

wav_files = [os.path.join(wav_dir, f) for f in os.listdir(wav_dir) if f.lower().endswith(".wav")]

lengths = []
for path in tqdm(wav_files, desc="Processing audio"):
    try:
        wav, sr = torchaudio.load(path)
        wav = wav.to(device)
        with torch.inference_mode():
            result = dac_model.encode(wav.unsqueeze(0))
            codes = result[0] if isinstance(result, tuple) else result
            T = codes.shape[-1]
            lengths.append(T)
    except Exception as e:
        print(f"❌ Error on {path}: {e}")

series = pd.Series(lengths)
print("\n=== Audio Frame Stats (DAC tokens) ===")
print(f"Total files : {len(lengths)}")
print(f"Max         : {series.max()}")
print(f"95th %ile   : {int(series.quantile(0.95))}")
print(f"Mean        : {int(series.mean())}")
print(f"Min         : {series.min()}")

/home/atmatech/.pyenv/versions/3.10.13/envs/dia-vox/lib/python3.10/site-packages/torch/nn/utils/weight_norm.py:143: FutureWarning: `torch.nn.utils.weight_norm` is deprecated in favor of `torch.nn.utils.parametrizations.weight_norm`.
  WeightNorm.apply(module, name, dim)
Processing audio: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4970/4970 [03:23<00:00, 24.42it/s]

=== Audio Frame Stats (DAC tokens) ===
Total files : 4970
Max         : 1015
95th %ile   : 776
Mean        : 521
Min         : 202

## Text Length

In [22]:
import pandas as pd

csv_path = "/mnt/ssd/ifa/text-to-speech/IMS-Toucan/Data/dataset_commonvoice/metadata.csv"

df = pd.read_csv(csv_path, sep="|", header=None, names=["audio_path", "text"])

# hitung panjang dalam byte
byte_lengths = df["text"].apply(lambda x: len(str(x).encode("utf-8")))
series = byte_lengths

print("\n=== Text Byte Stats (Dia-1.6B style) ===")
print(f"Total samples: {len(series)}")
print(f"Max bytes    : {series.max()}")
print(f"95th %ile    : {int(series.quantile(0.95))}")
print(f"Mean bytes   : {int(series.mean())}")
print(f"Min bytes    : {series.min()}")

=== Text Byte Stats (Dia-1.6B style) ===
Total samples: 4970
Max bytes    : 160
95th %ile    : 103
Mean bytes   : 65
Min bytes    : 9

In [26]:
import pandas as pd

csv_path = "/mnt/ssd/ifa/text-to-speech/IMS-Toucan/Data/dataset_commonvoice/metadata.csv"

# Baca file CSV
df = pd.read_csv(csv_path, sep="|", header=None, names=["audio_path", "text"])

# Tambahkan ekstensi .wav ke nama file
df["audio_path"] = df["audio_path"].astype(str) + ".wav"

# Simpan kembali ke file CSV dengan delimiter |, tanpa header dan index
df.to_csv(csv_path, sep="|", index=False, header=False)

df

         audio_path                                               text
0        file_1.wav  Saya mendengarkan cerita membosankan dari tema...
1        file_2.wav                                        halo dunia!
2        file_3.wav                      Sudah makan? sudah sholat...?
3        file_4.wav                         mau pergi kemana hari ini?
4        file_5.wav                         udah keluar hasil testnya?
...             ...                                                ...
4965  file_4966.wav  Sekolah ini memiliki empat laboratorium komput...
4966  file_4967.wav                  Ada fazenda besar dan peternakan.
4967  file_4968.wav  Normal untuk menganggapnya sebagai velositas d...
4968  file_4969.wav  Saya harap saya tidak pernah mencemooh apa yan...
4969  file_4970.wav  Penggunaan telah dibuat dari genetika klasik d...

[4970 rows x 2 columns]

## Audio Duration

In [5]:
import torchaudio
import os

def get_total_audio_duration_and_count(folder_path, extensions={".wav", ".mp3", ".flac"}):
    total_seconds = 0.0
    file_count = 0
    for root, _, files in os.walk(folder_path):
        for file in files:
            if any(file.lower().endswith(ext) for ext in extensions):
                path = os.path.join(root, file)
                try:
                    waveform, sample_rate = torchaudio.load(path)
                    duration = waveform.shape[1] / sample_rate
                    total_seconds += duration
                    file_count += 1
                except Exception as e:
                    print(f"Failed to load {file}: {e}")
    total_hours = total_seconds / 3600
    return total_hours, file_count

# Ganti dengan path ke folder kamu
folder = "/mnt/ssd/ifa/text-to-speech/IMS-Toucan/Data/dataset_commonvoice/wav"
hours, count = get_total_audio_duration_and_count(folder)
print(f"Total audio duration: {hours:.2f} hours")
print(f"Total number of audio files: {count}")

Total audio duration: 7.68 hours
Total number of audio files: 4970

# MMS-Bible-ID

## Audio Length

In [2]:
import os
import torch
import torchaudio
import dac
from tqdm import tqdm
import pandas as pd


import os
os.environ["CUDA_VISIBLE_DEVICES"] = "2"

wav_dir = "/mnt/ssd/ifa/text-to-speech/IMS-Toucan/Data/dataset_mms_bible_id_all/wav"
device = "cuda" if torch.cuda.is_available() else "cpu"

dac_model = dac.DAC.load(dac.utils.download()).to(device)

wav_files = [os.path.join(wav_dir, f) for f in os.listdir(wav_dir) if f.lower().endswith(".wav")]

lengths = []
for path in tqdm(wav_files, desc="Processing audio"):
    try:
        wav, sr = torchaudio.load(path)
        wav = wav.to(device)
        with torch.inference_mode():
            result = dac_model.encode(wav.unsqueeze(0))
            codes = result[0] if isinstance(result, tuple) else result
            T = codes.shape[-1]
            lengths.append(T)
    except Exception as e:
        print(f"❌ Error on {path}: {e}")

series = pd.Series(lengths)
print("\n=== Audio Frame Stats (DAC tokens) ===")
print(f"Total files : {len(lengths)}")
print(f"Max         : {series.max()}")
print(f"95th %ile   : {int(series.quantile(0.95))}")
print(f"Mean        : {int(series.mean())}")
print(f"Min         : {series.min()}")

/home/atmatech/.pyenv/versions/3.10.13/envs/dia-vox/lib/python3.10/site-packages/torch/nn/utils/weight_norm.py:143: FutureWarning: `torch.nn.utils.weight_norm` is deprecated in favor of `torch.nn.utils.parametrizations.weight_norm`.
  WeightNorm.apply(module, name, dim)
Processing audio: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1728/1728 [01:02<00:00, 27.54it/s]

=== Audio Frame Stats (DAC tokens) ===
Total files : 1728
Max         : 1766
95th %ile   : 822
Mean        : 430
Min         : 25

## Text Length

In [3]:
import pandas as pd

csv_path = "/mnt/ssd/ifa/text-to-speech/IMS-Toucan/Data/dataset_mms_bible_id_all/metadata.csv"

df = pd.read_csv(csv_path, sep="|", header=None, names=["audio_path", "text"])

# hitung panjang dalam byte
byte_lengths = df["text"].apply(lambda x: len(str(x).encode("utf-8")))
series = byte_lengths

print("\n=== Text Byte Stats (Dia-1.6B style) ===")
print(f"Total samples: {len(series)}")
print(f"Max bytes    : {series.max()}")
print(f"95th %ile    : {int(series.quantile(0.95))}")
print(f"Mean bytes   : {int(series.mean())}")
print(f"Min bytes    : {series.min()}")

=== Text Byte Stats (Dia-1.6B style) ===
Total samples: 1728
Max bytes    : 741
95th %ile    : 358
Mean bytes   : 182
Min bytes    : 7

## Audio Duration

In [5]:
import torchaudio
import os

def get_total_audio_duration_and_count(folder_path, extensions={".wav", ".mp3", ".flac"}):
    total_seconds = 0.0
    file_count = 0
    for root, _, files in os.walk(folder_path):
        for file in files:
            if any(file.lower().endswith(ext) for ext in extensions):
                path = os.path.join(root, file)
                try:
                    waveform, sample_rate = torchaudio.load(path)
                    duration = waveform.shape[1] / sample_rate
                    total_seconds += duration
                    file_count += 1
                except Exception as e:
                    print(f"Failed to load {file}: {e}")
    total_hours = total_seconds / 3600
    return total_hours, file_count

# Ganti dengan path ke folder kamu
folder = "/mnt/ssd/ifa/text-to-speech/IMS-Toucan/Data/dataset_mms_bible_id_all/wav"
hours, count = get_total_audio_duration_and_count(folder)
print(f"Total audio duration: {hours:.2f} hours")
print(f"Total number of audio files: {count}")

Total audio duration: 6.61 hours
Total number of audio files: 1728

# TITML-IDN

## Audio Length

In [6]:
import os
import torch
import torchaudio
import dac
from tqdm import tqdm
import pandas as pd


import os
os.environ["CUDA_VISIBLE_DEVICES"] = "2"

wav_dir = "/mnt/ssd/nafish/text-to-speech/data/TITMLIDN_formatting/wavs"
device = "cuda" if torch.cuda.is_available() else "cpu"

dac_model = dac.DAC.load(dac.utils.download()).to(device)

wav_files = [os.path.join(wav_dir, f) for f in os.listdir(wav_dir) if f.lower().endswith(".wav")]

lengths = []
for path in tqdm(wav_files, desc="Processing audio"):
    try:
        wav, sr = torchaudio.load(path)
        wav = wav.to(device)
        with torch.inference_mode():
            result = dac_model.encode(wav.unsqueeze(0))
            codes = result[0] if isinstance(result, tuple) else result
            T = codes.shape[-1]
            lengths.append(T)
    except Exception as e:
        print(f"❌ Error on {path}: {e}")

series = pd.Series(lengths)
print("\n=== Audio Frame Stats (DAC tokens) ===")
print(f"Total files : {len(lengths)}")
print(f"Max         : {series.max()}")
print(f"95th %ile   : {int(series.quantile(0.95))}")
print(f"Mean        : {int(series.mean())}")
print(f"Min         : {series.min()}")

/home/atmatech/.pyenv/versions/3.10.13/envs/dia-vox/lib/python3.10/site-packages/torch/nn/utils/weight_norm.py:143: FutureWarning: `torch.nn.utils.weight_norm` is deprecated in favor of `torch.nn.utils.parametrizations.weight_norm`.
  WeightNorm.apply(module, name, dim)
Processing audio: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 340/340 [00:10<00:00, 31.76it/s]

=== Audio Frame Stats (DAC tokens) ===
Total files : 340
Max         : 635
95th %ile   : 509
Mean        : 328
Min         : 82

## Text Length

In [20]:
import pandas as pd

txt_path = "/mnt/ssd/nafish/text-to-speech/data/TITMLIDN_formatting/metadata.txt"

# Baca file txt dengan separator "|"
df = pd.read_csv(txt_path, sep="|", header=None, names=["audio_id", "normalized_text", "original_text"])

# Hitung panjang byte dari normalized_text
byte_lengths = df["normalized_text"].apply(lambda x: len(str(x).encode("utf-8")))
series = byte_lengths

print("\n=== Text Byte Stats (Dia-1.6B style) ===")
print(f"Total samples: {len(series)}")
print(f"Max bytes    : {series.max()}")
print(f"95th %ile    : {int(series.quantile(0.95))}")
print(f"Mean bytes   : {int(series.mean())}")
print(f"Min bytes    : {series.min()}")

=== Text Byte Stats (Dia-1.6B style) ===
Total samples: 340
Max bytes    : 155
95th %ile    : 127
Mean bytes   : 81
Min bytes    : 22

In [35]:
import pandas as pd

txt_path = "/mnt/ssd/nafish/text-to-speech/data/TITMLIDN_formatting/metadata.txt"

# Baca file txt
df = pd.read_csv(txt_path, sep="|", header=None, names=["audio_id", "normalized_text", "original_text"])

# Pertahankan hanya dua kolom: audio_id dan normalized_text
df = df[["audio_id", "normalized_text"]]

# Simpan kembali ke file txt dengan pemisah '|'
csv_path = "/mnt/ssd/nafish/text-to-speech/data/TITMLIDN_formatting/metadata.csv"
df.to_csv(csv_path, sep="|", index=False, header=False)

df

       audio_id                                    normalized_text
0    03-001.wav                         hai selamat pagi apa kabar
1    03-002.wav                    semoga ujiannya berjalan lancar
2    03-003.wav                           acara nontonnya jadi kan
3    03-004.wav                      apakah kamu sudah makan siang
4    03-005.wav                      nanti malam pulang jam berapa
..          ...                                                ...
335  03-339.wav  hasilnya akan kita laporkan kepada joint komit...
336  03-340.wav  perdana menteri jepang junichiro koizumi dan r...
337  03-341.wav  rencana gugatan itu terungkap dalam jumpa pers...
338  03-342.wav  ntt perjuangkan pembangunan tenau internasiona...
339  03-343.wav  selama tiga puluh tahun kita sudah mengalami d...

[340 rows x 2 columns]

## Audio Duration

In [10]:
import torchaudio
import os

def get_total_audio_duration_and_count(folder_path, extensions={".wav", ".mp3", ".flac"}):
    total_seconds = 0.0
    file_count = 0
    for root, _, files in os.walk(folder_path):
        for file in files:
            if any(file.lower().endswith(ext) for ext in extensions):
                path = os.path.join(root, file)
                try:
                    waveform, sample_rate = torchaudio.load(path)
                    duration = waveform.shape[1] / sample_rate
                    total_seconds += duration
                    file_count += 1
                except Exception as e:
                    print(f"Failed to load {file}: {e}")
    total_hours = total_seconds / 3600
    return total_hours, file_count

# Ganti dengan path ke folder kamu
folder = "/mnt/ssd/nafish/text-to-speech/data/TITMLIDN_formatting/wavs"
hours, count = get_total_audio_duration_and_count(folder)
print(f"Total audio duration: {hours:.2f} hours")
print(f"Total number of audio files: {count}")

Total audio duration: 0.72 hours
Total number of audio files: 340

# Sindodusc

## Audio Length

In [11]:
import os
import torch
import torchaudio
import dac
from tqdm import tqdm
import pandas as pd


import os
os.environ["CUDA_VISIBLE_DEVICES"] = "2"

wav_dir = "/mnt/ssd/nafish/text-to-speech/data/sindodusc_formatting/wavs"
device = "cuda" if torch.cuda.is_available() else "cpu"

dac_model = dac.DAC.load(dac.utils.download()).to(device)

wav_files = [os.path.join(wav_dir, f) for f in os.listdir(wav_dir) if f.lower().endswith(".wav")]

lengths = []
for path in tqdm(wav_files, desc="Processing audio"):
    try:
        wav, sr = torchaudio.load(path)
        wav = wav.to(device)
        with torch.inference_mode():
            result = dac_model.encode(wav.unsqueeze(0))
            codes = result[0] if isinstance(result, tuple) else result
            T = codes.shape[-1]
            lengths.append(T)
    except Exception as e:
        print(f"❌ Error on {path}: {e}")

series = pd.Series(lengths)
print("\n=== Audio Frame Stats (DAC tokens) ===")
print(f"Total files : {len(lengths)}")
print(f"Max         : {series.max()}")
print(f"95th %ile   : {int(series.quantile(0.95))}")
print(f"Mean        : {int(series.mean())}")
print(f"Min         : {series.min()}")

/home/atmatech/.pyenv/versions/3.10.13/envs/dia-vox/lib/python3.10/site-packages/torch/nn/utils/weight_norm.py:143: FutureWarning: `torch.nn.utils.weight_norm` is deprecated in favor of `torch.nn.utils.parametrizations.weight_norm`.
  WeightNorm.apply(module, name, dim)
Processing audio: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 363/363 [00:10<00:00, 36.21it/s]

=== Audio Frame Stats (DAC tokens) ===
Total files : 363
Max         : 288
95th %ile   : 225
Mean        : 155
Min         : 74

## Text Length

In [30]:
import pandas as pd

txt_path = "/mnt/ssd/nafish/text-to-speech/data/sindodusc_formatting/metadata.txt"

# Baca file txt dengan separator "|"
df = pd.read_csv(txt_path, sep="|", header=None, names=["audio_id", "normalized_text", "original_text"])

# Hitung panjang byte dari normalized_text
byte_lengths = df["normalized_text"].apply(lambda x: len(str(x).encode("utf-8")))
series = byte_lengths

print("\n=== Text Byte Stats (Dia-1.6B style) ===")
print(f"Total samples: {len(series)}")
print(f"Max bytes    : {series.max()}")
print(f"95th %ile    : {int(series.quantile(0.95))}")
print(f"Mean bytes   : {int(series.mean())}")
print(f"Min bytes    : {series.min()}")

=== Text Byte Stats (Dia-1.6B style) ===
Total samples: 363
Max bytes    : 81
95th %ile    : 69
Mean bytes   : 42
Min bytes    : 13

In [1]:
import pandas as pd

txt_path = "/mnt/ssd/nafish/text-to-speech/data/sindodusc_formatting/metadata.txt"

# Baca file txt
df = pd.read_csv(txt_path, sep="|", header=None, names=["audio_id", "normalized_text", "original_text"])

# Pertahankan hanya dua kolom: audio_id dan normalized_text
df = df[["audio_id", "normalized_text"]]

df["audio_id"] = df["audio_id"].astype(str) + ".wav"

# Simpan kembali ke file txt dengan pemisah '|'
csv_path = "/mnt/ssd/nafish/text-to-speech/data/sindodusc_formatting/metadata.csv"
df.to_csv(csv_path, sep="|", index=False, header=False)

df

              audio_id                                    normalized_text
0    G0008_0_S0001.wav  Siapa orang yang bertanya ini? tanya jaksa kre...
1    G0008_0_S0002.wav       Ya allah lucu sekali vita waktu masih kecil.
2    G0008_0_S0004.wav  Zidane memang hanya dua setengah musim membela...
3    G0008_0_S0005.wav  Segera mereka mencari anak itu dan mewartakan ...
4    G0008_0_S0006.wav         Hari ini mereka akan melakukan penelitian.
..                 ...                                                ...
358  G0008_0_S0490.wav  Bagi intan, segala profesi caisar harus selalu...
359  G0008_0_S0494.wav  Hari berikutnya, abdulrahman berusaha melakuka...
360  G0008_0_S0495.wav                         Makasih semua teman teman.
361  G0008_0_S0496.wav       Saya mohon maaf tidak ketahui, jawab setnov.
362  G0008_0_S0497.wav                         Saya mending jago myanmar.

[363 rows x 2 columns]

## Audio Duration

In [14]:
import torchaudio
import os

def get_total_audio_duration_and_count(folder_path, extensions={".wav", ".mp3", ".flac"}):
    total_seconds = 0.0
    file_count = 0
    for root, _, files in os.walk(folder_path):
        for file in files:
            if any(file.lower().endswith(ext) for ext in extensions):
                path = os.path.join(root, file)
                try:
                    waveform, sample_rate = torchaudio.load(path)
                    duration = waveform.shape[1] / sample_rate
                    total_seconds += duration
                    file_count += 1
                except Exception as e:
                    print(f"Failed to load {file}: {e}")
    total_hours = total_seconds / 3600
    return total_hours, file_count

# Ganti dengan path ke folder kamu
folder =  "/mnt/ssd/nafish/text-to-speech/data/sindodusc_formatting/wavs"
hours, count = get_total_audio_duration_and_count(folder)
print(f"Total audio duration: {hours:.2f} hours")
print(f"Total number of audio files: {count}")

Total audio duration: 0.36 hours
Total number of audio files: 363

# indspeech-teldialog

## Audio Length

In [15]:
import os
import torch
import torchaudio
import dac
from tqdm import tqdm
import pandas as pd


import os
os.environ["CUDA_VISIBLE_DEVICES"] = "2"

wav_dir = "/mnt/ssd/nafish/text-to-speech/data/indspeech_teldialog_lvcsr_fomatting/wav_files"
device = "cuda" if torch.cuda.is_available() else "cpu"

dac_model = dac.DAC.load(dac.utils.download()).to(device)

wav_files = [os.path.join(wav_dir, f) for f in os.listdir(wav_dir) if f.lower().endswith(".wav")]

lengths = []
for path in tqdm(wav_files, desc="Processing audio"):
    try:
        wav, sr = torchaudio.load(path)
        wav = wav.to(device)
        with torch.inference_mode():
            result = dac_model.encode(wav.unsqueeze(0))
            codes = result[0] if isinstance(result, tuple) else result
            T = codes.shape[-1]
            lengths.append(T)
    except Exception as e:
        print(f"❌ Error on {path}: {e}")

series = pd.Series(lengths)
print("\n=== Audio Frame Stats (DAC tokens) ===")
print(f"Total files : {len(lengths)}")
print(f"Max         : {series.max()}")
print(f"95th %ile   : {int(series.quantile(0.95))}")
print(f"Mean        : {int(series.mean())}")
print(f"Min         : {series.min()}")

/home/atmatech/.pyenv/versions/3.10.13/envs/dia-vox/lib/python3.10/site-packages/torch/nn/utils/weight_norm.py:143: FutureWarning: `torch.nn.utils.weight_norm` is deprecated in favor of `torch.nn.utils.parametrizations.weight_norm`.
  WeightNorm.apply(module, name, dim)
Processing audio: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:02<00:00, 40.65it/s]

=== Audio Frame Stats (DAC tokens) ===
Total files : 100
Max         : 294
95th %ile   : 210
Mean        : 140
Min         : 74

## Text Length

In [44]:
import pandas as pd

txt_path = "/mnt/ssd/nafish/text-to-speech/data/indspeech_teldialog_lvcsr_fomatting/metadata.txt"

# Baca file txt dengan separator "|"
df = pd.read_csv(txt_path, sep="|", header=None, names=["audio_id", "normalized_text", "original_text"])

# Hitung panjang byte dari normalized_text
byte_lengths = df["normalized_text"].apply(lambda x: len(str(x).encode("utf-8")))
series = byte_lengths

print("\n=== Text Byte Stats (Dia-1.6B style) ===")
print(f"Total samples: {len(series)}")
print(f"Max bytes    : {series.max()}")
print(f"95th %ile    : {int(series.quantile(0.95))}")
print(f"Mean bytes   : {int(series.mean())}")
print(f"Min bytes    : {series.min()}")

=== Text Byte Stats (Dia-1.6B style) ===
Total samples: 100
Max bytes    : 69
95th %ile    : 50
Mean bytes   : 28
Min bytes    : 9

In [47]:
import pandas as pd

# Path ke file txt
txt_path = "/mnt/ssd/nafish/text-to-speech/data/indspeech_teldialog_lvcsr_fomatting/metadata.txt"  # Ganti dengan path sebenarnya
output_path = "/mnt/ssd/nafish/text-to-speech/data/indspeech_teldialog_lvcsr_fomatting/metadata.csv"  # Ganti sesuai kebutuhan

# Baca file txt
df = pd.read_csv(txt_path, sep="|", header=None, names=["audio_id", "normalized_text", "original_text"])

# Tambahkan ekstensi .wav ke audio_id
df["audio_id"] = df["audio_id"].astype(str) + ".wav"

# Pertahankan hanya dua kolom: audio_id dan normalized_text
df = df[["audio_id", "normalized_text"]]

# Simpan ke CSV dengan delimiter | tanpa header dan tanpa index
df.to_csv(output_path, sep="|", index=False, header=False)

## Audio Duration

In [17]:
import torchaudio
import os

def get_total_audio_duration_and_count(folder_path, extensions={".wav", ".mp3", ".flac"}):
    total_seconds = 0.0
    file_count = 0
    for root, _, files in os.walk(folder_path):
        for file in files:
            if any(file.lower().endswith(ext) for ext in extensions):
                path = os.path.join(root, file)
                try:
                    waveform, sample_rate = torchaudio.load(path)
                    duration = waveform.shape[1] / sample_rate
                    total_seconds += duration
                    file_count += 1
                except Exception as e:
                    print(f"Failed to load {file}: {e}")
    total_hours = total_seconds / 3600
    return total_hours, file_count

# Ganti dengan path ke folder kamu
folder =  "/mnt/ssd/nafish/text-to-speech/data/indspeech_teldialog_lvcsr_fomatting/wav_files"
hours, count = get_total_audio_duration_and_count(folder)
print(f"Total audio duration: {hours:.2f} hours")
print(f"Total number of audio files: {count}")

Total audio duration: 0.09 hours
Total number of audio files: 100

In [ ]:
csv_path = "/mnt/ssd/nafish/text-to-speech/data/indspeech_news_tts/dia_dataset.csv"
csv_path = "/mnt/ssd/nafish/text-to-speech/data/commonvoice/metadata.csv"
csv_path = "/mnt/ssd/nafish/text-to-speech/data/TITMLIDN_formatting/metadata.csv"
csv_path = "/mnt/ssd/nafish/nafish/text-to-speech/data/sindodusc_formatting/metadata.csv"
csv_path = "/mnt/ssd/nafish/text-to-speech/data/indspeech_teldialog_lvcsr_fomatting/metadata.csv"

wav_path = "/mnt/ssd/nafish/text-to-speech/data/indspeech_news_tts/wavs"
wav_path = "/mnt/ssd/nafish/text-to-speech/data/commonvoice/wav"
wav_path = "/mnt/ssd/nafish/text-to-speech/data/TITMLIDN_formatting/wavs"
wav_path = "/mnt/ssd/nafish/text-to-speech/data/sindodusc_formatting/wavs"
wav_path = "/mnt/ssd/nafish/text-to-speech/data/indspeech_teldialog_lvcsr_fomatting/wav_files"

In [2]:
import pandas as pd

# List file csv dan root path-nya
datasets = [
    {
        "csv_path": "/mnt/ssd/nafish/text-to-speech/data/indspeech_news_tts/dia_dataset.csv",
        "root": "indspeech_news_tts/wavs"
    },
    {
        "csv_path": "/mnt/ssd/nafish/text-to-speech/data/commonvoice/metadata.csv",
        "root": "commonvoice/wav"
    },
    {
        "csv_path": "/mnt/ssd/nafish/text-to-speech/data/TITMLIDN_formatting/metadata.csv",
        "root": "TITMLIDN_formatting/wavs"
    },
    {
        "csv_path": "/mnt/ssd/nafish/text-to-speech/data/sindodusc_formatting/metadata.csv",
        "root": "sindodusc_formatting/wavs"
    },
    {
        "csv_path": "/mnt/ssd/nafish/text-to-speech/data/indspeech_teldialog_lvcsr_fomatting/metadata.csv",
        "root": "indspeech_teldialog_lvcsr_fomatting/wav_files"
    }
]

# Gabungkan semua
all_data = []

for dataset in datasets:
    df = pd.read_csv(dataset["csv_path"], sep="|", header=None, names=["audio_path", "text"])
    df["audio_path"] = df["audio_path"].apply(lambda x: f"{dataset['root']}/{x}")
    all_data.append(df)

# Gabungkan semua DataFrame
final_df = pd.concat(all_data, ignore_index=True)

# Simpan sebagai CSV dengan delimiter |
final_df.to_csv("/mnt/ssd/nafish/text-to-speech/data/combined_dataset.csv", sep="|", index=False, header=False)

In [3]:
final_df.tail(20)

,audio_path,text
7765,indspeech_teldialog_lvcsr_fomatting/wav_files/...,Gimana prosedur bikin akte kelahiran?
7766,indspeech_teldialog_lvcsr_fomatting/wav_files/...,Proses IMB saya sampai mana?
7767,indspeech_teldialog_lvcsr_fomatting/wav_files/...,Enam pas.
7768,indspeech_teldialog_lvcsr_fomatting/wav_files/...,Apakah NPWP saya bisa diambil selasa minggu ini?
7769,indspeech_teldialog_lvcsr_fomatting/wav_files/...,Tutup hanya jendela utama saja.
7770,indspeech_teldialog_lvcsr_fomatting/wav_files/...,Apakah sensor satu on?
7771,indspeech_teldialog_lvcsr_fomatting/wav_files/...,Matikan selama sembilan puluh menit.
7772,indspeech_teldialog_lvcsr_fomatting/wav_files/...,Divisi marketing.
7773,indspeech_teldialog_lvcsr_fomatting/wav_files/...,Mohon info mengenai pengurusan SHM.
7774,indspeech_teldialog_lvcsr_fomatting/wav_files/...,Gimana cara bikinnya?
7775,indspeech_teldialog_lvcsr_fomatting/wav_files/...,Apakah HGB saya bisa kelar kamis ini?
7776,indspeech_teldialog_lvcsr_fomatting/wav_files/...,Prosesnya sampai mana?
7777,indspeech_teldialog_lvcsr_fomatting/wav_files/...,Bisa booking audioconference?
7778,indspeech_teldialog_lvcsr_fomatting/wav_files/...,Matikan semua sensor.
7779,indspeech_teldialog_lvcsr_fomatting/wav_files/...,Apakah ruangan keluarga terang?
7780,indspeech_teldialog_lvcsr_fomatting/wav_files/...,Apakah pintu tiga tertutup?
7781,indspeech_teldialog_lvcsr_fomatting/wav_files/...,Dua pagi.
7782,indspeech_teldialog_lvcsr_fomatting/wav_files/...,Untuk hari ini pukul sembilan nol nol WIB.
7783,indspeech_teldialog_lvcsr_fomatting/wav_files/...,Tagihan PLN.
7784,indspeech_teldialog_lvcsr_fomatting/wav_files/...,Apakah KTP saya bisa selesai kamis ini?

In [59]:
df = pd.read_csv("/mnt/ssd/nafish/text-to-speech/data/combined_dataset.csv", sep="|", header=None, names=["audio_path", "text"])
df

,audio_path,text
0,indspeech_news_tts/wavs/SPK00_F_0000.wav,Reaksi berbeda disampaikan penasihat hukum pe...
1,indspeech_news_tts/wavs/SPK00_F_0001.wav,Konflik eksekutif-legislatif sebenarnya adala...
2,indspeech_news_tts/wavs/SPK00_F_0002.wav,Jenderal TNI Endriartono Sutarto memuji sosok...
3,indspeech_news_tts/wavs/SPK00_F_0003.wav,Ketua fraksi PDIP Arifin Panigoro dan Yusril ...
4,indspeech_news_tts/wavs/SPK00_F_0004.wav,"Yakni Gubernur Sutiyoso, Djaelani, Fauzi Bowo..."
...,...,...
7517,indspeech_teldialog_lvcsr_fomatting/wav_files/...,Apakah pintu tiga tertutup?
7518,indspeech_teldialog_lvcsr_fomatting/wav_files/...,Dua pagi.
7519,indspeech_teldialog_lvcsr_fomatting/wav_files/...,Untuk hari ini pukul sembilan nol nol WIB.
7520,indspeech_teldialog_lvcsr_fomatting/wav_files/...,Tagihan PLN.
7521,indspeech_teldialog_lvcsr_fomatting/wav_files/...,Apakah KTP saya bisa selesai kamis ini?

In [1]:
import pandas as pd
from g2p_id import G2P

# Inisialisasi G2P
g2p = G2P()

# Path ke file CSV input dan output
input_csv = "/mnt/ssd/nafish/text-to-speech/data/combined_dataset.csv"  # ganti sesuai file kamu
output_csv = "/mnt/ssd/nafish/text-to-speech/data/combined_dataset_phoneme.csv"

# Baca CSV
df = pd.read_csv(input_csv, sep="|", header=None, names=["audio_path", "grapheme_text"])

# Ubah grapheme ke phoneme
df["phoneme_text"] = df["grapheme_text"].apply(g2p)

# Tulis ulang CSV hanya dengan audio_path dan phoneme_text
df[["audio_path", "phoneme_text"]].to_csv(output_csv, sep="|", index=False, header=False)

In [2]:
import pandas as pd

phoneme_csv_path = "/mnt/ssd/nafish/text-to-speech/data/combined_dataset_phonem.csv"

# Baca file CSV hasil phonemization
df = pd.read_csv(phoneme_csv_path, sep="|", header=None, names=["audio_id", "phoneme_text"])

# Hitung panjang byte dari phoneme_text
byte_lengths = df["phoneme_text"].apply(lambda x: len(str(x).encode("utf-8")))
series = byte_lengths

print("\n=== Phoneme Text Byte Stats (Dia-1.6B style) ===")
print(f"Total samples: {len(series)}")
print(f"Max bytes    : {series.max()}")
print(f"95th %ile    : {int(series.quantile(0.95))}")
print(f"Mean bytes   : {int(series.mean())}")
print(f"Min bytes    : {series.min()}")

=== Phoneme Text Byte Stats (Dia-1.6B style) ===
Total samples: 7785
Max bytes    : 221
95th %ile    : 138
Mean bytes   : 83
Min bytes    : 3

In [ ]:
nohup python -m dia.finetune \
  --config /mnt/ssd/nafish/text-to-speech/dia-finetuning/dia/config.json \
  --csv_path /mnt/ssd/nafish/text-to-speech/data/combined_dataset.csv \
  --audio_root /mnt/ssd/nafish/text-to-speech/data \
  --hub_model nari-labs/Dia-1.6B \
  --run_name dia-indspeech-news-tts-4 \
  --output_dir /mnt/ssd/nafish/text-to-speech/dia-finetuning/ft-combined-dataset-22072025 \
  > dia-finetuning-combined-dataset-22072025.out &

In [ ]:
nohup python -m dia.finetune \
  --config /mnt/ssd/nafish/text-to-speech/dia-finetuning/dia/config.json \
  --csv_path /mnt/ssd/nafish/text-to-speech/data/combined_dataset_phoneme.csv \
  --audio_root /mnt/ssd/nafish/text-to-speech/data \
  --hub_model nari-labs/Dia-1.6B \
  --run_name dia-indspeech-news-tts-5 \
  --output_dir /mnt/ssd/nafish/text-to-speech/dia-finetuning/ft-combined-dataset-phoneme-22072025 \
  > dia-finetuning-combined-dataset-phoneme-22072025.out &